version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env # Ensure this path is correct
    volumes:
      - .:/app # Mount current directory to /app in container
    entrypoint: /entrypoint.sh # Use entrypoint script
    environment:
      DATABASE_URL: "postgres://postgres:${DATABASE_PASSWORD}@/mydb?host=/cloudsql/cool-artwork-445504:europe-central2:postgre123"
    command: gunicorn --workers 3 --bind 0.0.0.0:8080 puddle.wsgi
