version: '3.8'

services:
  django:
    build: .
    container_name: django
    command: gunicorn --bind 0.0.0.0:8000 puddle.wsgi:application  # Use Gunicorn for production
    volumes:
      - .:/app  # Mount the code into the container
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"  # Expose Django on port 8000
    env_file:
      - .env  # Load environment variables from .env file
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount Nginx config file
      - static_volume:/app/static  # Mount the static files directory
      - media_volume:/app/media  # Mount the media files directory (optional)
    ports:
      - "80:80"  # Expose Nginx on port 80
    networks:
      - webnet

volumes:
  static_volume:
  media_volume:

networks:
  webnet:
    driver: bridge
