name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          ENGINE: django.db.backends.postgresql
          NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}  # Use GitHub secrets for sensitive data
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8  # Install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Wait for PostgreSQL to be ready
      run: |
        while ! pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 2
        done

    - name: Run Django tests
      working-directory: puddle
      run: |
        python manage.py test core.tests conversation.tests dashboard.tests item.tests
      env:
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}  # Make sure to set this in GitHub secrets
        DATABASE_HOST: localhost  # Use localhost if PostgreSQL service is on the same machine in GitHub Actions
        DATABASE_PORT: 5432
        DATABASE_NAME: postgres
        DATABASE_USER: postgres
